### ISSUE TITLE
Make the index... an index

### ISSUE THREAD

**Issue by sammcj** [FallibleInc/security-guide-for-developers#20]
- Idea: Make the index points hyperlinks like [1. The Security Checklist](security-checklist.md).

- Reasoning: It currently looks like there's no content, but maybe I am stupid.

- Alternative Solution: I'll accept that I'm stupid and you can close my ticket because I missed something of which I'm sure you'll inform me of when you close this issue.

**Comment by maxaille** [comment]
It looks how it should looks actually: with not many content at this time ;-)

**Comment by sammcj** [comment]
Yay - so I'm not stupid and I should contribute right?

**Comment by maxaille** [comment]
Not an author, but looking at the current Pull Request, maybe you can try

**Comment by sammcj** [comment]
Sorry, my last comment was a little tongue and cheek, that's interesting though because I've been watching this repo get posted _everywhere_ today but have also been quite busy, so giving it a half glance I was somewhat confused, now that I know - I will close my own comment, admit to self realisation instead of stupidity and commit to contributing soon. (pun intended)

**Comment by abhishek-anand** [comment]
@sammcj You are most welcome to contribute to the guide :) We have received a lot of feedback at different places and will be adding the other contents gradually.
