### ISSUE TITLE
Make it easier to find out more

### ISSUE THREAD

**Issue by jdtzmn** [FallibleInc/security-guide-for-developers#35]
I really like the idea of this repository, and I was actually recently wondering if a repository like this existed, but it would be really helpful if you could include links for each of the checklist items to places were one could find out how they can implement it into their own code.

I was looking down the checklist, and for some of the items I had no idea what it was. It would be really awesome if someone could add links so that you can learn more about the ones that aren't necessarily as clear as others.

Thanks!

**Comment by danielmelogpi** [comment]
This would be great!
But I worry about how to make it generic enough to allow devs across many stacks to take advantage of it. May-be a page detailing each one with examples in a variety of languages.

**Comment by Matthalp** [comment]
+1

Would it be overkill to develop a toy example application that demonstrates as many of these best practices as possible? Perhaps dockerized as well.

**Comment by danielmelogpi** [comment]
I think it would... 😃
But I would like it, nonetheless

**Comment by burowaqw** [comment]
+1

**Comment by makflwana** [comment]
http://webdevchecklist.com - look at this one

**Comment by mkagenius** [comment]
@jdtzmn @danielmelogpi @Matthalp We are writing details for each item in contents. It will cover all the items in the checklist and more.
